//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Jatekos_id { get; set; }
        public string Jatekos_nev { get; set; }
        public Nullable<int> Golok { get; set; }
        public Nullable<int> Golpasszok { get; set; }
        public Nullable<decimal> Jatekperc { get; set; }
        public string Poszt { get; set; }
        public string Csapat { get; set; }
    }
}
