//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Jatekos_Id { get; set; }
        public string Jatekos_nev { get; set; }
        public Nullable<int> Gol { get; set; }
        public Nullable<int> Golpassz { get; set; }
        public Nullable<decimal> Jatekperc { get; set; }
        public Nullable<int> Poszt_fk { get; set; }
        public string Csapat { get; set; }
    
        public virtual Table2 Table2 { get; set; }
    }
}
